version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/1510-FEC
    steps:
      - checkout
      - run:
          name: 'install dependencies'
          command: npm install
      - run:
          name: 'run frontend tests'
          command: npm run test
      # - run:
      #     name: 'cd into backend'
      #     command: pwd
      # command: |
      #       $ProgressPreference = "SilentlyContinue"
      #       Compress-Archive .\\<< parameters.label >> .\\<< parameters.label >>.zip
      # - run: 'list working directory'
      #     command: ls
      - run:
          name: 'run backend tests'
          command: npm --prefix ./backend run test

workflows:
  build_and_test:
    jobs:
      - test
