version: 2.1

# # Potentially set up orb for npm in the future
# orbs:
#   node: circleci/node@4.2.0


# Define the jobs we want to run for this project
jobs:
  test:
    working_directory: ~/client
    docker:
      - image: cimg/node:14.15.4
  steps:
    - checkout
    # potentially add cache set up for optimization in the future
    - run:
        name: 'install dependencies'
        command: npm install
    - run:
        name: 'run tests'
        command: npm run test

# Define workflow
workflows:
  build_and_test:
    jobs:
      - test
